language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --source=authors/ manage.py test
  - coverage report -m
  - coveralls

after_script:
  #- coveralls
