language: python

python:
  - "3.5.2"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c "create database ah;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source=authors/ manage.py test
  - coverage report -m
  - coveralls

after_script:
  #- coveralls
