# Generated by Django 2.1 on 2018-09-06 13:26

import authors.apps.social_auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(default=authors.apps.social_auth.utils.create_unique_number, max_length=255),
        ),
    ]
