# Generated by Django 2.1 on 2018-09-24 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(error_messages={'required': 'Write a short title for your article.'}, max_length=255)),
                ('description', models.TextField(error_messages={'required': 'A description of your post is required.'})),
                ('body', models.TextField(error_messages={'required': 'You cannot submit an article without body.'})),
                ('favorites_count', models.IntegerField(default=0)),
                ('photo_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at', 'author'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_message', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('body', models.TextField(error_messages={'required': 'You cannot submit without a comment.'})),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('-score',),
            },
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('content', models.TextField(error_messages={'required': 'You cannot submit without a reply.'})),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
