# Generated by Django 2.1 on 2018-09-14 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(error_messages={'required': 'Write a short title for your article.'},
                                           max_length=255)),
                ('description',
                 models.TextField(error_messages={'required': 'A description of your post is required.'})),
                ('body', models.TextField(error_messages={'required': 'You cannot submit an article without body.'})),
                ('favorited', models.BooleanField(default=False)),
                ('favorites_count', models.IntegerField(default=0)),
                ('photo_url', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'author'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
